### ISSUE TITLE
Could not compile `c2rust-refactor`

### ISSUE THREAD

**Issue by phodina** [immunant/c2rust#185] opened 2019-10-27 23:37 UTC
I'm using docker to build c2rust, however, it won't compile.

```shell
[docker@docker C2Rust]$ cargo build
   Compiling c2rust-refactor v0.13.0 (/home/docker/C2Rust/c2rust-refactor)
error: could not compile `c2rust-refactor`.

Caused by:
  process didn't exit successfully: `rustc --edition=2018 --crate-name c2rust_refactor c2rust-refactor/src/lib.rs --color always --crate-type lib --emit=dep-info,metadata,link -C debuginfo=2 --cfg 'feature="default"' -C metadata=055eb39ba0edac90 -C extra-filename=-055eb39ba0edac90 --out-dir /home/docker/C2Rust/target/debug/deps -C incremental=/home/docker/C2Rust/target/debug/incremental -L dependency=/home/docker/C2Rust/target/debug/deps --extern c2rust_ast_builder=/home/docker/C2Rust/target/debug/deps/libc2rust_ast_builder-95f5314f2df5b5d9.rmeta --extern c2rust_ast_printer=/home/docker/C2Rust/target/debug/deps/libc2rust_ast_printer-d53a82eeb8671082.rmeta --extern c2rust_macros=/home/docker/C2Rust/target/debug/deps/libc2rust_macros-e97c6960cdd4a8b2.so --extern cargo=/home/docker/C2Rust/target/debug/deps/libcargo-97712247616a4390.rmeta --extern clap=/home/docker/C2Rust/target/debug/deps/libclap-3595967ef6812243.rmeta --extern derive_more=/home/docker/C2Rust/target/debug/deps/libderive_more-13ea2de10ad9ad8d.so --extern diff=/home/docker/C2Rust/target/debug/deps/libdiff-3f0b48764debc633.rmeta --extern ena=/home/docker/C2Rust/target/debug/deps/libena-876e09c4891b0201.rmeta --extern env_logger=/home/docker/C2Rust/target/debug/deps/libenv_logger-c83039b78e762984.rmeta --extern indexmap=/home/docker/C2Rust/target/debug/deps/libindexmap-9b9a20c623688e15.rmeta --extern json=/home/docker/C2Rust/target/debug/deps/libjson-f08e385776eda7e1.rmeta --extern libc=/home/docker/C2Rust/target/debug/deps/liblibc-0e0048e8e461acd8.rmeta --extern log=/home/docker/C2Rust/target/debug/deps/liblog-e65dadbe05044a3e.rmeta --extern regex=/home/docker/C2Rust/target/debug/deps/libregex-4a135d35714c34d6.rmeta --extern rlua=/home/docker/C2Rust/target/debug/deps/librlua-053a1a37bb3e8c1e.rmeta --extern slotmap=/home/docker/C2Rust/target/debug/deps/libslotmap-8f4c1f83f5337ae5.rmeta -L native=/usr/lib -L native=/home/docker/C2Rust/target/debug/build/libnghttp2-sys-f307e45e1aca7b4b/out/i/lib -L native=/usr/lib -L native=/home/docker/C2Rust/target/debug/build/backtrace-sys-50045560fc541810/out -L native=/home/docker/C2Rust/target/debug/build/miniz-sys-2be7d37ef2123f33/out -L native=/home/docker/C2Rust/target/debug/build/libgit2-sys-3ad7109f68c35d0e/out/build -L native=/home/docker/C2Rust/target/debug/build/libssh2-sys-88e12764ff351f97/out/build -L native=/home/docker/C2Rust/target/debug/build/rlua-cafeba349a5e88ec/out` (signal: 9, SIGKILL: kill)
```

**Comment by thedataking** [comment] 2019-10-28 18:00
This could be caused by the kernel running out of memory. Could you try again while keeping an eye on memory consumption?

**Comment by virtualritz** [comment] 2020-01-28 03:23
I have a similar issue on my 2014 MBP:
```
error: failed to execute compile
caused by: error reading compile response from server
caused by: Failed to read response header
caused by: failed to fill whole buffer
error: failed to compile `c2rust v0.14.0`, intermediate artifacts can be found at `/var/folders/7w/h5916h8d28n3cy1pvfpn2xc00000gn/T/cargo-installBIv3hu`

Caused by:
  could not compile `c2rust-refactor`.
```

Maybe it would be possible to do binary releases of this for the most common platforms (Win/macOS/Linux)?

**Comment by thedataking** [comment] 2020-01-29 23:45
@virtualritz: It sounds like you are using `sscache` to build c2rust. This is not something we've tried but my best guess is that you're either seeing timeouts or running out of memory. Maybe you can try some of the `sscache` workarounds (such as increasing the timeout threshold) suggested here: https://github.com/mozilla/sccache/issues/256. Failing that, could you try to build without `sscache`? 

We spent a lot of time to make sure that `cargo install` works on a large range of platforms, so crates.io is our preferred distribution mechanism.  Hope you're able to get the issue resolved!

**Comment by kkysen** [comment] 2022-06-29 03:32
Closing as `c2rust-refactor` in its current form is no longer being developed.

**Closed by kkysen** 2022-06-29 03:32 UTC
Labels: question, wontfix, refactorer
