### ISSUE TITLE
c2rust not installing on Ubuntu 22.10

### ISSUE THREAD

**Issue by jejdouay** [immunant/c2rust#717] opened 2022-11-05 00:59 UTC
I tried to install the c2rust 0.16 using the cargo install c2rust.

during the compilation process, it actually throw me a all bunch of error due to missing packages. I solved that problem.

However, at the end, using LLVM 15 I have this error

/home/jerome/.cargo/registry/src/github.com-1ecc6299db9ec823/c2rust-ast-exporter-0.16.0/src/AstExporter.cpp: In lambda function:
/home/jerome/.cargo/registry/src/github.com-1ecc6299db9ec823/c2rust-ast-exporter-0.16.0/src/AstExporter.cpp:2248:52: error: ‘Ascii’ is not a member of ‘clang::StringLiteral::StringKind’
2248 |             case clang::StringLiteral::StringKind::Ascii:

It does not look like something I can fix with a missing package. does anyone knows how to solve this problem ?

**Comment by kkysen** [comment] 2022-11-05 01:08
Duplicate of #713 and #676 and fixed in #677.

**Closed by kkysen** 2022-11-05 01:08 UTC
Labels: duplicate
