### ISSUE TITLE
ast_exporter error after each file about -p

### ISSUE THREAD

**Issue by boomshroom** [immunant/c2rust#40] opened 2019-03-01 21:42 UTC
`ast_exporter: for the -p option: may only occur zero or one times!`

This error gets printed after each file and it stops. However if I rerun it, it progresses anyways and skips previously translated files, which after a quick visual inspection, didn't simply get outputted as empty files. I couldn't find anywhere this error might be coming from or any similar errors from Googling. I can complete this anyways, but it means running c2rust once for every file, or which the project I'm currently working on has 866.

**Comment by rinon** [comment] 2019-03-01 21:51
This looks like an error coming from Clang. Could you post one of the command invocations from your `compile_commands.json` file?

**Comment by boomshroom** [comment] 2019-03-01 22:31
One of the files that errored:

```
        "arguments": [
            "/nix/store/mcn38j1hlyqmbqijm7hh3agvsq8x95vm-clang-5.0.2/bin/clang", 
            "-c", 
            "-O2", 
            "-D_FORTIFY_SOURCE=2", 
            "-fstack-protector-strong", 
            "--param", 
            "ssp-buffer-size=4", 
            "-fno-strict-overflow", 
            "-Wformat", 
            "-Wformat-security", 
            "-Werror=format-security", 
            "-fPIC", 
            "-DHAVE_CONFIG_H", 
            "-I../ncurses", 
            "-I.", 
            "-I../include", 
            "-D_GNU_SOURCE", 
            "-D_DEFAULT_SOURCE", 
            "-DTRACE", 
            "--param", 
            "max-inline-insns-single=1200", 
            "-B/nix/store/jhryl7nxal3j6931by5yd95biibrwkc5-clang-5.0.2-lib/lib", 
            "-resource-dir=/nix/store/pa7qir0l7d6mcq56n5ny15iwyrfxm6mn-clang-wrapper-5.0.2/resource-root", 
            "--gcc-toolchain=/nix/store/g8wz2x9ai0i3rkl0h09ydz20jfwbgjfk-gcc-7.4.0", 
            "-B/nix/store/sw54ph775lw7b9g4hlfvpx6fmlvdy8qi-glibc-2.27/lib/", 
            "-idirafter", 
            "/nix/store/qmg2fkspkzl0xsdqpmg3k06bmgp27saz-glibc-2.27-dev/include", 
            "-B/nix/store/pa7qir0l7d6mcq56n5ny15iwyrfxm6mn-clang-wrapper-5.0.2/bin/", 
            "-isystem", 
            "/nix/store/mvrwg7wszcaj5iyxgd80xyrr0ph55dsl-compiler-rt-5.0.2-dev/include", 
            "-isystem", 
            "/nix/store/mvrwg7wszcaj5iyxgd80xyrr0ph55dsl-compiler-rt-5.0.2-dev/include", 
            "-isystem", 
            "/nix/store/mvrwg7wszcaj5iyxgd80xyrr0ph55dsl-compiler-rt-5.0.2-dev/include", 
            "-isystem", 
            "/nix/store/mvrwg7wszcaj5iyxgd80xyrr0ph55dsl-compiler-rt-5.0.2-dev/include", 
            "-isystem", 
            "/nix/store/mvrwg7wszcaj5iyxgd80xyrr0ph55dsl-compiler-rt-5.0.2-dev/include", 
            "-o", 
            "../objects/captoinfo.o", 
            "tinfo/captoinfo.c"
        ], 
        "directory": "/home/angelo/src/rust/riir/ncurses-6.1/ncurses", 
        "file": "tinfo/captoinfo.c"
    }, 
```

By testing in a fresh directory, it managed to translate 1 properly, and then failed the second. There might be some state that isn't properly getting reset between translation units.

**Comment by boomshroom** [comment] 2019-03-01 22:34
After doing some more testing, the error persists even if I remove all flags from c2rust's invocation.

**Comment by rinon** [comment] 2019-03-01 22:54
It might be picking up the wrong clang libraries. We've seen a similar problem where both static and dynamic clang libraries got linked into c2rust. Are you building with cargo or with `scripts/build_translator.py`? I'd recommend trying to build with cargo and link against your system clang libs, if you're not doing that already.

**Comment by boomshroom** [comment] 2019-03-01 23:07
Built with cargo, that said...

> link against your system clang libs

On NixOS, there is no "system clang libs" just like there's no "system anything libs". That said, they should have used the same version.

**Comment by rinon** [comment] 2019-03-01 23:21
I'm not very familiar with NixOS, but you can have dependencies on other packages, like clang (see [how cquery does this](https://github.com/NixOS/nixpkgs/blob/060bcd6df50bf2e61efe7b14b0458e83d72adc87/pkgs/development/tools/misc/cquery/default.nix#L23)). However, that's not going to do you much good as we don't support Clang 5 and that seems to be the latest nixpkg version available. You will probably need to keep using our build script that pulls down and builds the clang libraries.

I'm guessing whatever is going on here is NixOS-specific. I don't have time to figure out how to install and run Nix right now to debug this, but I'll see when I can get around to it. In the mean time, can you take a look at the verbose output of `cargo build` when using our build script (add `./scripts/build_translator.py --verbose`). I'm specifically interested in the linker invocation and what library search paths are being used.

**Comment by boomshroom** [comment] 2019-03-01 23:52
I'm actually having a hard time running build_translater.py because of Python. It's not even reaching cargo at all. First I was supplying python3 and it found python2 from my user environment and claimed it was version 1.4. Then I switched python3 for python2.7 and got `ImportError: dynamic module does not define module export function (PyInit__psutil_linux)`.

P.S. Python is one of my least favourite programming languages.

**Comment by thedataking** [comment] 2019-03-15 19:19
@boomshroom where you able to resolve your problems?

**Comment by boomshroom** [comment] 2019-03-15 23:16
I don't think so, I just worked around it by calling repeatedly and haven't used it since.

**Comment by thedataking** [comment] 2019-03-15 23:55
Okay; thanks for getting back to us. We don't have enough information to reproduce and troubleshoot the issue. We'll close it for now but feel free to reopen if you want to run this to ground. If you don't absolutely have to translate on NixOS, you might want to give our [prebuilt docker images](https://hub.docker.com/r/immunant/c2rust) a try.

**Closed by thedataking** 2019-03-15 23:55 UTC
