### ISSUE TITLE
`#__has_include` results in errors when false

### ISSUE THREAD

**Issue by Dante-Broggi** [immunant/c2rust#561] opened 2022-07-28 03:42 UTC
I tried:
```c
// test.c
#if __has_include("no_file.h")
#include "no_file.h"
#endif
```
```sh
intercept-build sh -c "\$CC test.c"
c2rust transpile compile_commands.json
```
I got:
```shell
test.c:2:19: fatal error: cannot open file './no_file.h': No such file or directory
#if __has_include("no_file.h")
                  ^
1 error generated.
Error while processing /TMP/test.c.
Transpiling test.c
```

This is on MacOS Monterey with brew c2rust version `C2Rust 0.16.0 (2022-07-19)`
I don't know if it is actually fatal for c2rust, but either it is and shouldn't be, or it shouldn't be saying so on stderr.

**Comment by kkysen** [comment] 2022-07-28 19:50
I'm testing this on linux so maybe it's different on macOS, but I'm not getting any transpiler errors with this.

I do get this:

```shell
❯ intercept-build sh -c "\$CC test.c"
sh: 1: test.c: not found
```

and if I do this:

```shell
❯ intercept-build sh -c "cc test.c"
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/11/../../../x86_64-linux-gnu/Scrt1.o: in function `_start':
(.text+0x1b): undefined reference to `main'
collect2: error: ld returned 1 exit status
```

I get an error because `main` isn't defined.  Then if I add main,

```c
// test.c
#if __has_include("no_file.h")
#include "no_file.h"
#endif

int main() {}
```

then it works and I get a `compile_commands.json`:

```json
[
    {
        "arguments": [
            "cc",
            "-c",
            "test.c"
        ],
        "directory": "/home/kkysen/work/rust/c2rust-playground",
        "file": "test.c"
    }
]
```

And then transpiling works fine:

```shell
❯ c2rust transpile compile_commands.json
Transpiling test.c
```

@Dante-Broggi, what does your `compile_commands.json` look like?

**Comment by Dante-Broggi** [comment] 2022-07-28 21:24
The `compile_commands.json` which is generated (with and without `main`) is:
```json
[
    {
        "arguments": [
            "cc",
            "-c",
            "test.c"
        ],
        "directory": "/Users/dantebroggi/tmp/c2rs",
        "file": "test.c"
    }
]
```

the error occurs when calling `c2rust transpile compile_commands.json`

**Comment by kkysen** [comment] 2022-07-28 21:48
What llvm/clang are you linking against?  Can you also try a `cargo install c2rust` `c2rust`?  The `brew` one is very new and not maintained by us.

**Comment by kkysen** [comment] 2022-08-02 03:48
As far as I can tell, this seems to work, so I'm closing this.  @Dante-Broggi, if you have more info and are sure it's still crashing, we can re-open it.

**Closed by kkysen** 2022-08-02 03:48 UTC
Labels: bug

**Comment by kornelski** [comment] 2022-09-15 10:01
This doesn't work for me with c2rust version 00ace7631 2022-09-07 and brew's llvm: stable 14.0.6.

```text
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/math.h:31:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/Availability.h:136:
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/AvailabilityInternal.h:33:19: fatal error: cannot open file '/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/AvailabilityInternalPrivate.h': No such file or directory
#if __has_include(<AvailabilityInternalPrivate.h>)
```

**Comment by kkysen** [comment] 2022-09-15 10:04
Could you show us your minimal C file and `compile_commands.json`?  It seems like this might be a macOS issue, as I could never reproduce it on Linux.

**Comment by kornelski** [comment] 2022-09-15 10:08
I've created compile commands with `bear -- make all` and `all: file.o`. I can't share the full file, but the errors are in common system headers:

```c
#include <math.h>
#include <stdint.h>
#include <stdio.h>
#include <string.h>
#include <time.h>
#include <x86intrin.h>
```

Note that this won't be reproducible on Linux. Apple doesn't support gcc, and uses their own dialect of clang-specific C.

**Comment by kkysen** [comment] 2022-09-15 10:10
`c2rust` uses `clang`, though.

You can't trim down that file to just the offending standard headers `#include`s and `#__has_include`s?  It'd be quite hard to debug without that.

**Comment by kornelski** [comment] 2022-09-15 10:27
I mean `#include <math.h>` is the entire file you need to reproduce the issue. There's nothing more to trim.

**Comment by kkysen** [comment] 2022-09-15 10:31
Oh, you're not using `#if __has_include` yourself, it's somewhere within `math.h`?  Could you open a new issue for this then?
