### ISSUE TITLE
Static struct

### ISSUE THREAD

**Issue by boomshroom** [immunant/c2rust#39] opened 2019-03-01 21:11 UTC
I'm trying to translate ncurses for fun and I ran into a few files that contained a line like `static const NCURSES_CH_T blankchar = NewChar(BLANK_TEXT);`. When c2rust hit those files, it panicked with

```
thread 'main' panicked at 'internal error: entered unreachable code: Found static initializer type other than block or array: Struct(path(cchar_t), [Field { ident: attr#0, expr: expr(4294967040: ' ' as i32 as chtype & !1u32.wrapping_sub(1u32) << 0i32 + 8i32), span: Span { lo: BytePos(0), hi: BytePos(0), ctxt: #0 }, is_shorthand: false, attrs: ThinVec(None) }, Field { ident: chars#0, expr: expr(4294967040: [(' ' as i32 as chtype & (1u32 << 0i32 + 8i32).wrapping_sub(1u32)) as wchar_t, 0i32, 0i32, 0i32, 0i32]), span: Span { lo: BytePos(0), hi: BytePos(0), ctxt: #0 }, is_shorthand: false, attrs: ThinVec(None) }, Field { ident: ext_color#0, expr: expr(4294967040: 0i32), span: Span { lo: BytePos(0), hi: BytePos(0), ctxt: #0 }, is_shorthand: false, attrs: ThinVec(None) }], None)', c2rust-transpile/src/translator/mod.rs:897:26
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

The culprit is fairly clearly c2rust-transpile/src/translator/mod.rs#L897 and it seems like c2rust simply didn't expect this to happen. From what I can tell, it shouldn't be too hard to translate static struct initializers into rust especially since rust already supports them.

So far, I've been working around this by replacing the static structures with `#define`s.

**Comment by ahomescu** [comment] 2019-03-01 21:19
We already support translating static struct initializers, and I think the real culprit here is:
```C
#define ChCharOf(c)	((chtype)(c) & (chtype)A_CHARTEXT)
#define ChAttrOf(c)	((chtype)(c) & (chtype)A_ATTRIBUTES)
...
#define NewChar(ch)	NewChar2(ChCharOf(ch), ChAttrOf(ch))
```

I'll check if we support bitwise `&` in static initializers, I suspect that's might be the problem.

**Comment by TheDan64** [comment] 2019-03-01 21:20
Yeah, this seems to be one that rust won't compile in a static and so we have to initialize it in a section. We'll see if we can get this to work. I think it should be possible

**Comment by ahomescu** [comment] 2019-03-01 22:07
We have a potential fix in ad0e0421c04c32bfce7ebfd354c251e9fd980164, @boomshroom could you give it another try?

**Comment by thedataking** [comment] 2019-04-14 04:17
@boomshroom please let us know if the issue is fixed for you so that we may close the issue.

**Comment by rinon** [comment] 2019-10-03 01:59
Closing for inactivity, please ping this issue if you need it re-opened.

**Closed by rinon** 2019-10-03 01:59 UTC
