### ISSUE TITLE
Transpiled program does not compile when assigning a `bool` with `&=` in the C code.

### ISSUE THREAD

**Issue by VorpalBlade** [immunant/c2rust#831] opened 2023-02-13 23:40 UTC
Given (this much reduced test case):

```c
#include <stdio.h>
#include <stdint.h>
#include <stdbool.h>

int32_t *
i32_strstr(const int32_t *haystack_start,
           const int32_t *needle_start)
{
    const int32_t *haystack = haystack_start;
    const int32_t *needle = needle_start;
    bool ok = true; /* True if NEEDLE is prefix of HAYSTACK.  */

    /* Determine length of NEEDLE, and in the process, make sure
       HAYSTACK is at least as long (no point processing all of a long
       NEEDLE if HAYSTACK is too short).  */
    while (*haystack && *needle)
        ok &= *haystack++ == *needle++;

    // Rest of code cut, not needed to demo this conversion issue.
    return 0;
}

int main(void) {
    int32_t weird_haystack[] = {1, 2, 3, 0};
    int32_t weird_needle[] = {1, 2, 0};
    printf("%p\n", i32_strstr(weird_haystack, weird_needle));
    return 0;
}
```

The transpiled code looks like:

```rust
#![allow(dead_code, mutable_transmutes, non_camel_case_types, non_snake_case, non_upper_case_globals, unused_assignments, unused_mut)]
use ::c2rust_out::*;
extern "C" {
    fn printf(_: *const libc::c_char, _: ...) -> libc::c_int;
}
pub type __int32_t = libc::c_int;
pub type int32_t = __int32_t;
#[no_mangle]
pub unsafe extern "C" fn i32_strstr(
    mut haystack_start: *const int32_t,
    mut needle_start: *const int32_t,
) -> *mut int32_t {
    let mut haystack: *const int32_t = haystack_start;
    let mut needle: *const int32_t = needle_start;
    let mut ok: bool = 1 as libc::c_int != 0;
    while *haystack != 0 && *needle != 0 {
        let fresh0 = haystack;
        haystack = haystack.offset(1);
        let fresh1 = needle;
        needle = needle.offset(1);
        ok = (ok as libc::c_int & (*fresh0 == *fresh1) as libc::c_int) as bool;
    }
    return 0 as *mut int32_t;
}
unsafe fn main_0() -> libc::c_int {
    let mut weird_haystack: [int32_t; 4] = [
        1 as libc::c_int,
        2 as libc::c_int,
        3 as libc::c_int,
        0 as libc::c_int,
    ];
    let mut weird_needle: [int32_t; 3] = [
        1 as libc::c_int,
        2 as libc::c_int,
        0 as libc::c_int,
    ];
    printf(
        b"%p\n\0" as *const u8 as *const libc::c_char,
        i32_strstr(weird_haystack.as_mut_ptr(), weird_needle.as_mut_ptr()),
    );
    return 0 as libc::c_int;
}
pub fn main() {
    unsafe { ::std::process::exit(main_0() as i32) }
}
```

This does not compile:
```
error[E0054]: cannot cast as `bool`
  --> test.rs:21:14
   |
21 |         ok = (ok as libc::c_int & (*fresh0 == *fresh1) as libc::c_int) as bool;
   |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: compare with zero instead: `(ok as libc::c_int & (*fresh0 == *fresh1) as libc::c_int) != 0`
```

Software versions:
* Arch Linux (rolling release distro).
* glibc 2.37-2
* clang 15.0.7-1
* rustc 1.67.1 (from rustup)
* c2rust 0.17.0 (from cargo install)

**Comment by kkysen** [comment] 2023-02-18 09:11
Duplicate of #340 (see https://github.com/immunant/c2rust/issues/340#issuecomment-1378248070).

**Closed by kkysen** 2023-02-18 09:11 UTC
