### ISSUE TITLE
Installation error with latest rustc-demangle

### ISSUE THREAD

**Issue by ankane** [immunant/c2rust#350] opened 2021-09-14 02:15 UTC
Hi, thanks for this project! I wanted to report an error during installation with `rustc-demangle`.

```sh
cargo +nightly-2019-12-05 install c2rust
```

Error

```text
error[E0658]: use of unstable library feature 'matches_macro'
   --> /Users/andrew/.cargo/registry/src/github.com-1ecc6299db9ec823/rustc-demangle-0.1.21/src/v0.rs:700:20
    |
700 |                 if matches!((quote, c), ('\'', '"') | ('"', '\'')) {
    |                    ^^^^^^^
    |
    = note: for more information, see https://github.com/rust-lang/rust/issues/65721
    = help: add `#![feature(matches_macro)]` to the crate attributes to enable
```

It appears to be due to [this change](https://github.com/rust-lang/rustc-demangle/commit/6b3c45971be29c06693c6c38c8650dbce5a592f5) in rustc-demangle 0.1.21, which uses the `matches!` macro, which isn't stable in `nightly-2019-12-05`.

**Comment by thedataking** [comment] 2021-09-14 03:38
Have you tried `cargo +nightly-2019-12-05 install c2rust --locked`? If so, this is likely a duplicate of #323.

**Comment by ankane** [comment] 2021-09-14 05:12
Thanks @thedataking, looks like that fixed it. A few suggestions to make it easier for new users:

1. Would be good to merge #335 to add `--locked` to the readme instructions
2. `--locked` doesn't seem to work with the "Installing from Git" instructions (possibly https://github.com/rust-lang/cargo/issues/7495). I think this can be updated to:

```sh
git clone https://github.com/immunant/c2rust.git
cd c2rust
cargo +nightly-2019-12-05 install --path c2rust --locked
```

3. On Mac, `brew install llvm` installs LLVM 12, which isn't doesn't appear to be supported by the latest release. Would be good to either make a new release with dfa995c89ede1f803dd361d67309ee8b681d0d29 or update the Mac instructions to `brew install llvm@9` and `LLVM_CONFIG_PATH=/usr/local/opt/llvm@9/bin/llvm-config`.

**Closed** 2022-02-08 03:12 UTC
