### ISSUE TITLE
Installation fails with crates.io version

### ISSUE THREAD

**Issue by jbteves-sandia** [immunant/c2rust#1149] opened 2024-10-23 15:15 UTC
Currently, on crates.io, the version is listed as 0.18, not 0.19 as is listed on this repo, and fails with the following error when building using `cargo install c2rust` with no additional flags on cargo version 1.82.0.
```
error[E0282]: type annotations needed for `Box<_>`
  --> [REDACTED]/index.crates.io-6f17d22bba15001f/time-0.3.18/src/format_description/parse/mod.rs:83:9
   |
83 |     let items = format_items
   |         ^^^^^
...
86 |     Ok(items.into())
   |              ---- type must be known at this point
   |
   = note: this is an inference error on crate `time` caused by an API change in Rust 1.80.0; update `time` to version `>=0.3.35` by calling `cargo update`

For more information about this error, try `rustc --explain E0282`.
```
However, installing from source works fine:
```
cargo install --git https://github.com/immunant/c2rust.git c2rust
[spew]
Installed package `c2rust v0.19.0 (https://github.com/immunant/c2rust.git#516b30e3)` (executables `c2rust`, `c2rust-transpile`)
```

**Comment by kkysen** [comment] 2024-11-18 10:31
This is fundamentally a duplicate of #1125 (see https://github.com/immunant/c2rust/issues/1125#issuecomment-2482621726), so I'm closing this to centralize things there.  Once we properly publish 0.20.0, this issue should be fixed.

**Closed by kkysen** 2024-11-18 10:31 UTC
