### ISSUE TITLE
failed to run custom build command for `c2rust-ast-exporter v0.16.0`

### ISSUE THREAD

**Issue by MurraySobol** [immunant/c2rust#787] opened 2023-01-19 16:28 UTC
I'm getting this error on Windows 11; I found fixes for other platforms, but not for Windows 11.
 More info:

```sh
Caused by:
  process didn't exit successfully: `C:\Users\murra\AppData\Local\Temp\cargo-installTxdqRq\release\build\c2rust-ast-exporter-29ae4383fe719000\build-script-build` (exit code: 101)
  --- stderr
  thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "The system cannot find the file specified." }', C:\Users\murra\.cargo\registry\src\github.com-1ecc6299db9ec823\c2rust-ast-exporter-0.16.0\build.rs:226:34
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: failed to compile `c2rust v0.16.0`, intermediate artifacts can be found at `C:\Users\murra\AppData\Local\Temp\cargo-installTxdqRq`
```

**Comment by fw-immunant** [comment] 2023-01-19 19:54
I believe this is a duplicate of https://github.com/immunant/c2rust/issues/463.

**Closed by fw-immunant** 2023-01-19 19:54 UTC
