### ISSUE TITLE
Static Builds Using MUSL Target Fail

### ISSUE THREAD

**Issue by sempervictus** [immunant/c2rust#322] opened 2021-01-09 08:40 UTC
When using the following to build:
```
  pacman -Sy rustup --noconfirm
  TC="nightly-2019-12-05"
  rustup install "$TC"
  rustup target add x86_64-unknown-linux-musl --toolchain="$TC"
  rustup component add rustc-dev --target=x86_64-unknown-linux-musl --toolchain="$TC"
```
the `rustc_macros` crate cannot be found:
```
   Compiling rand_jitter v0.1.4
error[E0463]: can't find crate for `rustc_macros` which `rustc` depends on
 --> c2rust-ast-builder/src/lib.rs:2:1
  |
2 | extern crate rustc;
  | ^^^^^^^^^^^^^^^^^^^ can't find crate

error: aborting due to previous error

For more information about this error, try `rustc --explain E0463`.
error: could not compile `c2rust-ast-builder`.
```
This is all on Arch Linux x86_64

**Comment by okias** [comment] 2021-01-24 21:45
rust-nightly-x86_64-unknown-linux-gnu.tar.xz + rustc-dev.

I can confirm similar error when building https://github.com/servo/servo/ . 

My first though after readinf this issue is to downgrade to older version

**Comment by sempervictus** [comment] 2021-01-26 03:56
Given that i'm using that 2019 version and relevant toochain, what am i doing wrong? Someone else noted that it doesnt compile on Arch as is since i filed this, so hoping to make it static to avoid the whole rolling release concern around brittle builds.

**Comment by thedataking** [comment] 2021-01-26 08:28
Musl is not supported because of issue https://github.com/immunant/c2rust/issues/243. It appears that the issue has been fixed in a May 2020 toolchain but alas we are on a December 2019 toolchain (until we find time to roll it forward).

**Comment by okias** [comment] 2021-01-26 14:05
My issue was likely unrelated, since it was caused by flatpak **stripping or spliting and compressing** debug stuff from **rustc-dev** .

**Comment by fw-immunant** [comment] 2022-05-16 12:30
This should be fixed by our recent upgrades (away from using rustc crates in the transpiler, and supporting compiling with rustc 1.58 stable, nightly-2021-11-22, or later).

**Comment by sempervictus** [comment] 2022-05-16 12:32
Thank you @fw-immunant - will try to get a build run to verify

**Comment by kkysen** [comment] 2022-06-29 04:15
I believe all of `c2rust`('s default features) and most of its dependencies build fine on musl, but I'm seeing issues with `*-sys` crates (such as `openssl-sys` and `libz-sys`) and needing a cross-compiling `pkg-config`.  I'll see if I can statically compile with musl once I figure those issues out.

**Comment by kkysen** [comment] 2022-06-29 21:44
Closing as the `*-sys` crates issues cross-compiling aren't related to `c2rust` and should work when not cross-compiling.

**Closed by kkysen** 2022-06-29 21:44 UTC
Labels: building
