### ISSUE TITLE
Using LLVM to translate C++ to C to Rust

### ISSUE THREAD

**Issue by mczarnek** [immunant/c2rust#235] opened 2020-02-07 18:38 UTC
I'm seeing rumors that LLVM can transpile C++ to C.. which you could then transpile to Rust.

Would be nice if you guys could use that or another C++ to C transpiler to allow transpiling C++ as well.

**Comment by XVilka** [comment] 2020-03-06 08:31
Duplicate of https://github.com/immunant/c2rust/issues/162 ?

**Comment by thedataking** [comment] 2020-03-06 16:34
@mczarnek thanks for letting us know that you'd like to see C++ support!  A goal of this project is to generate human-readable Rust which is already hard to do for C. To support C++, we think the "right" approach is to extend the transpiler to recognize C++ constructs (at least the ones that have counterparts in Rust) and handle them directly vs. relying on a third-party tool that "flattens" C++ down to C. 

@XVilka yes, thanks, closing this one in favor of #162.

**Closed by thedataking** 2020-03-06 16:34 UTC
Labels: duplicate
